### ISSUE TITLE
单独一个中文引号经常造成无法匹配

### ISSUE THREAD

**Issue by wnsacc** [veasion/syntax-parse#1]
String dialog="主持人：“请问你有兄弟姐妹吗？”，选手：“我还有一个妹妹。”";
String template1="[主持人：“][#主持人问题:[W:1-100]][”，][选手：“][#选手回答:[W:1-100]][”]";
String template2="[主持人：“][#主持人问题:[W:1-100]][”][，选手：“][#选手回答:[W:1-100]][”]";
使用template1可以正常匹配，使用template2则无法匹配
![image](https://github.com/veasion/syntax-parse/assets/20176432/451aea24-d39a-4f62-a882-8f5fd2f4cae5)
但是这种单独引号换一个位置，例如最后面那个[”]，或者下面这种情况：
String template3="[主持人：][“][#主持人问题:[W:1-100]][”，][选手：“][#选手回答:[W:1-100]][”]";
是可以匹配的。

**Comment by veasion** [comment]
尽量不要用一个字的短语句作为模板规则， 其中有一个变量  Syntax.MAX_MATCH 默认为 true ，意思是按最大匹配，匹配逻辑大概是这样的，每匹配一个 Syntax 时都会预测下一个 Syntax 是否能匹配，如果能匹配则进入下一轮匹配，template2 模板中匹配 “主持人问题” 的时候 长度范围是 1-100 然后下一个 Syntax 是 “”” ，正好第 30 个字符也是 “”” 所以它直接匹配到了 0-29 个字符（满足最大匹配）。

不建议使用单个字符的 Syntax ，如果你要这样做把  Syntax.MAX_MATCH = false; 这样它就能正常匹配了。

也可以改代码，把逻辑改成尽量匹配 下下个 Syntax 或者 下下下个 Syntax （后续我有时间优化下这块代码）

**Comment by veasion** [comment]
![image](https://github.com/veasion/syntax-parse/assets/24989778/bfbcb469-4ac0-4f3e-acc1-8eaf152d7124)

**Comment by wnsacc** [comment]
好的，感谢
